config/routes.rb
UserTutorial::Application.routes.draw do

  root to: "static_pages#home"

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/firms/:firm_id/recipes', to: 'recipes#index'
  match '/batches/qualityCheck/:id', to:'batches#qualityCheck'
  match 'bakeries/:id', to: 'bakeries#show', as: 'bakery', via: [:get, :post]
  
  resources :users
  resources :clients
  
  resources :firms
  resources :bakeries
  resources :huslabs

  resources :recipes
  resources :materials
  resources :substances
  resources :eluates
  resources :radiomedicines
  resources :generators, :controller => :batches
  resources :others, :controller => :batches
  resources :kits, :controller => :batches
  resources :storagelocations
  resources :batches
  resources :bakeryorders
  resources :bills

  resources :products, :controller => :recipes
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/_footer.html.haml
%footer.footer.span12
  %small &copy Tmi Janne Laukkanen 2013
  - #= link_to 'Devlfin', "http://devlfin.com/"        
  %nav
    %ul
      %li= link_to "Tietoa",  about_path
      %li= link_to "Ota yhteyttä",    contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    %div
      .pull-left
        - if false
          %small.center#current-firm
            Yritys:
            - if current_user.primary_firm
              = link_to current_user.primary_firm.name, current_user.primary_firm
            - else
              = link_to current_user.firms.first.name, current_user.firms.first
      .pull-right
        - if signed_in? 
          %small.center#logged-in-user
            Kirjautunut:
            = link_to current_user.name, current_user
          %small.center#cur-time
            |
            = Time.now.strftime("%d.%m.%Y %H:%M")
      %div.container
        = link_to image_tag("logo.png"), root_path, { id: "logo" }
        %nav
          %ul.nav.pull-right
            %li.divider-vertical
            %li
              - if current_user && current_user.primary_firm
                - if current_user.primary_firm.resource_type == "Bakery"
                  = link_to :controller => "bakeries", :action => "show", :id => current_user.primary_firm.id do
                    %i.icon-home.icon-white
                - elsif current_user.primary_firm.resource_type == "Huslab"
                  = link_to :controller => "huslabs", :action => "show", :id => current_user.primary_firm.id do
                    %i.icon-home.icon-white
              - else 
                - if current_user && current_user.firms && current_user.firms.first
                  - if current_user.firms.first.resource_type == "Bakery"
                    = link_to :controller => "bakeries", :action => "show", :id => current_user.firms.first.id do
                      %i.icon-home.icon-white
                  - elsif current_user.firms.first.resource_type == "Huslab"
                    = link_to :controller => "huslabs", :action => "show", :id => current_user.firms.first.id do
                      %i.icon-home.icon-white
            - if signed_in?
              %li#fat-menu.dropdown 
                %a{class: "dropdown-toggle", href: "#", data: {toggle: "dropdown"}} 
                  %i.icon-cog.icon-white
                  <b class="caret"></b> 
                
                %ul.dropdown-menu{role:"menu"}
                  - if is_admin?
                    %li
                      = link_to controller: :users, action: :index do
                        %i.icon-user.icon
                        Käyttäjät
                  %li
                    = link_to controller: :firms, action: :index do
                      %i.icon-list.icon
                      Yritykset
                  %li
                    = link_to controller: :users, action: :show , id: current_user.id do
                      %i.icon-user.icon
                      Profiili
                  %li
                    = link_to edit_user_path(current_user) do
                      %i.icon-wrench.icon
                      Asetukset
                  %li.divider
                  %li
                    = link_to signout_path, method: "delete" do
                      %i.icon-off.icon
                      Kirjaudu ulos
            - else
              %li
                = link_to controller: :sessions, action: :new do
                  %i.icon-chevron-right.icon-white
                  Kirjaudu
          %ul.nav.pull-right
            - if current_user && current_user.primary_firm && current_user.primary_firm.resource_type == "Bakery"
              = render "layouts/bakery"
            - elsif current_user && current_user.primary_firm && current_user.primary_firm.resource_type == "Huslab"
              = render "layouts/huslab"

app/views/layouts/_huslab.html.haml
%li
  = link_to :controller => "eluates", :action => "index", :huslab_id => current_user.primary_firm.resource.id do
    Eluaatit
%li
  = link_to :controller => "radiomedicines", :action => "index", :huslab_id => current_user.primary_firm.resource.id do
    Radiolääkkeet
%li
  = link_to :controller => "storagelocations", :action => "index", :huslab_id => current_user.primary_firm.resource.id do
    Varastopaikat
%li
  = link_to :controller => "substances", :action => "index", :huslab_id => current_user.primary_firm.resource.id do
    Raaka-aineet